version: "3"
services: 
  app:
    restart: unless-stopped
    container_name: app
    build: .
    ports:
      - 3001:3001
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      CLIENT_BASE_URI: "${CLIENT_BASE_URI}"
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_USE_SSL: "${DATABASE_USE_SSL}"
    depends_on:
      - app_db

  app_db:
    restart: unless-stopped
    image: postgres:15.3
    container_name: app_db
    ports:
      - 5443:5432
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  nginx:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
        - 80:80/tcp
        - 443:443/tcp
    environment:
        CERTBOT_EMAIL: pbarreiro@gmail.com
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt

volumes:
  pgdata:
  letsencrypt: