version: "3"
services: 
  app:
    container_name: app
    build: .
    ports:
      - 3001:3001
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      CLIENT_BASE_URI: "${CLIENT_BASE_URI}"
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_USE_SSL: "${DATABASE_USE_SSL}"
    depends_on:
      - app_db

  app_db:
    image: postgres:15.3
    container_name: app_db
    ports:
      - 5443:5432
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: